### ISSUE TITLE
LSFScripts/SplitInput_ArrayJob.q missing

### ISSUE THREAD

**Issue by fmaguire** [brian-cleary/LatentStrainAnalysis#1]
Doesn't appear to be included in the repository so setupDirs.py is throwing an error, is this meant to be generated using create_jobs.py?

**Comment by brian-cleary** [comment]
setupDirs.py should be creating this file, so it doesn't need to be
included.

See line 41: f = open('LSFScripts/SplitInput_ArrayJob.q','w')

Maybe you're working in another directory, and so LSFScripts doesn't exist?

**Comment by fmaguire** [comment]
Ah yeah, sorry was being stupid with relpaths.  Thanks.
